import { Translate } from '../models/entities/translate';

export const translates: Translate[] = [
  { key: 'addition', languageId: 1, value: 'Toplama' },
  { key: 'addition', languageId: 2, value: 'Addition' },

  { key: 'subtraction', languageId: 1, value: 'Çıkarma' },
  { key: 'subtraction', languageId: 2, value: 'Subtraction' },

  { key: 'multiplication', languageId: 1, value: 'Çarpma' },
  { key: 'multiplication', languageId: 2, value: 'Multiplication' },

  { key: 'division', languageId: 1, value: 'Bölme' },
  { key: 'division', languageId: 2, value: 'Division' },

  { key: 'leftParantheses', languageId: 1, value: 'Sol Parantez' },
  { key: 'leftParantheses', languageId: 2, value: 'Left Parantheses' },
  { key: 'rightParantheses', languageId: 1, value: 'Sağ Parantez' },
  { key: 'rightParantheses', languageId: 2, value: 'Right Parantheses' },
  { key: 'sin', languageId: 1, value: 'Sinüs' },
  { key: 'sin', languageId: 2, value: 'Sinus' },
  { key: 'cos', languageId: 1, value: 'Kosinüs' },
  { key: 'cos', languageId: 2, value: 'Cosinus' },
  { key: 'tan', languageId: 1, value: 'Tanjant' },
  { key: 'tan', languageId: 2, value: 'Tanjant' },
  { key: 'seq', languageId: 1, value: 'Sekant' },
  { key: 'seq', languageId: 2, value: 'Secant' },
  { key: 'csc', languageId: 1, value: 'Kosekant' },
  { key: 'csc', languageId: 2, value: 'Cosecant' },
  { key: 'cot', languageId: 1, value: 'Kotantant' },
  { key: 'cot', languageId: 2, value: 'Cotanjant' },
  { key: 'power', languageId: 1, value: 'Üs' },
  { key: 'power', languageId: 2, value: 'Power' },
  { key: 'squareRoot', languageId: 1, value: 'Karekök' },
  { key: 'squareRoot', languageId: 2, value: 'Square Root' },
  { key: 'minus', languageId: 1, value: 'Eksi' },
  { key: 'minus', languageId: 2, value: 'Minus' },
  { key: 'language', languageId: 1, value: 'Dil' },
  { key: 'language', languageId: 2, value: 'Language' },
  { key: 'operation', languageId: 1, value: 'İşlem' },
  { key: 'operation', languageId: 2, value: 'Operation' },
  { key: 'symbol', languageId: 1, value: 'İşaret' },
  { key: 'symbol', languageId: 2, value: 'Symbol' },
  { key: 'changeLanguage', languageId: 1, value: 'Dili Değiştir' },
  { key: 'changeLanguage', languageId: 2, value: 'Change Language' },
  { key: 'drawFunctionGraph', languageId: 1, value: 'Fonksiyon Grafiğini Çiz' },
  { key: 'drawFunctionGraph', languageId: 2, value: 'Draw Function Graph' },
  { key: 'calculate', languageId: 1, value: 'Hesapla' },
  { key: 'calculate', languageId: 2, value: 'Calculate' },
  { key: 'enterAValueToCalculate', languageId: 1, value: 'Hesaplamak için bir değer girin' },
  { key: 'enterAValueToCalculate', languageId: 2, value: 'Enter a value to calculate' },
  { key: 'enterMaxDisplayValue', languageId: 1, value: 'Maks. gösterim sayısını girin' },
  { key: 'enterMaxDisplayValue', languageId: 2, value: 'Enter max display value' },
  { key: 'functionInput', languageId: 1, value: 'Fonksiyonu girin' },
  { key: 'functionInput', languageId: 2, value: 'Enter function' },
  { key: 'maxDisplayValue', languageId: 1, value: 'Maks. gösterim sayısı' },
  { key: 'maxDisplayValue', languageId: 2, value: 'Max display value' },
  { key: 'result', languageId: 1, value: 'Sonuç' },
  { key: 'result', languageId: 2, value: 'Result' },
];
